//! Owned, serde-friendly mirror of [`patches_core::ModuleDescriptorTemplate`]
//! plus the [`ModuleManifest`] envelope (ADR 0066, ticket 0791).
//!
//! In-tree modules describe themselves with `&'static`-backed templates in
//! `patches-core`. The manifest serializes those templates so consumers
//! (LSP, SVG renderer, FFI plugin shells) can read module shape data
//! without linking `patches-modules`.

use patches_core::{
    cables::{CableKind, MonoLayout, PolyLayout},
    AxisId, CountAxis, ModuleDescriptorTemplate, ParameterKind, ParameterTemplate, PortTemplate,
};
use serde::{Deserialize, Serialize};

pub mod static_registry;

mod bundled {
    use super::ModuleManifest;
    use std::sync::OnceLock;

    const BUNDLED_MANIFEST_JSON: &str = include_str!("../data/module-manifest.json");

    /// Parse the in-tree default-registry manifest checked in at
    /// `patches-manifest/data/module-manifest.json`. Cached for the
    /// lifetime of the process.
    ///
    /// # Panics
    ///
    /// Panics at first call (process startup) if the bundled JSON does
    /// not deserialize. The file is regenerated by
    /// `patches-manifest --json --deterministic` and the schema is
    /// snapshot-tested in `patches-tools`, so a deserialization failure
    /// here means the in-tree JSON drifted from `OwnedTemplate` and the
    /// corresponding snapshot test would also be failing in CI.
    pub fn bundled_manifest() -> &'static ModuleManifest {
        static CACHE: OnceLock<ModuleManifest> = OnceLock::new();
        CACHE.get_or_init(|| {
            // SAFETY: panic contract documented on `bundled_manifest`.
            serde_json::from_str(BUNDLED_MANIFEST_JSON)
                .expect("bundled module-manifest.json must deserialize")
        })
    }
}

pub use bundled::bundled_manifest;

/// Re-exported so consumers building a registry from a manifest do not
/// need a direct path dep on `patches-registry`. ADR 0067 forbids
/// `patches-svg`/`patches-lsp` → `patches-registry`; routing through
/// `patches-manifest` keeps that edge clean.
pub use patches_core::registry::Registry;

/// Bumped on any breaking change to the on-disk manifest schema.
pub const SCHEMA_VERSION: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct GeneratorInfo {
    pub tool: String,
    pub git_rev: String,
    pub timestamp: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ModuleManifest {
    pub schema_version: u32,
    pub generator: GeneratorInfo,
    pub modules: Vec<ModuleManifestEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ModuleManifestEntry {
    pub name: String,
    pub template: OwnedTemplate,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OwnedTemplate {
    pub name: String,
    pub axes: Vec<OwnedAxis>,
    pub global_inputs: Vec<OwnedPort>,
    pub per_axis_inputs: Vec<(OwnedAxisId, OwnedPort)>,
    pub global_outputs: Vec<OwnedPort>,
    pub per_axis_outputs: Vec<(OwnedAxisId, OwnedPort)>,
    pub realtime_params: Vec<OwnedParam>,
    pub structural_params: Vec<OwnedParam>,
    pub per_axis_realtime_params: Vec<(OwnedAxisId, OwnedParam)>,
    pub per_axis_structural_params: Vec<(OwnedAxisId, OwnedParam)>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OwnedAxisId(pub String);

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OwnedAxis {
    pub id: OwnedAxisId,
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OwnedPort {
    pub name: String,
    pub kind: OwnedCableKind,
    pub mono_layout: OwnedMonoLayout,
    pub poly_layout: OwnedPolyLayout,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OwnedParam {
    pub name: String,
    pub kind: OwnedParamKind,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum OwnedCableKind {
    Mono,
    Poly,
    Stereo,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum OwnedMonoLayout {
    Audio,
    Trigger,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum OwnedPolyLayout {
    Audio,
    Trigger,
    Transport,
    Midi,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum OwnedParamKind {
    Float { min: f32, max: f32, default: f32 },
    Int { min: i64, max: i64, default: i64 },
    Bool { default: bool },
    Enum { variants: Vec<String>, default: String },
    File { extensions: Vec<String> },
    SongName,
}

// ── From impls: static → owned ──────────────────────────────────────────

impl From<&AxisId> for OwnedAxisId {
    fn from(a: &AxisId) -> Self {
        Self(a.0.to_string())
    }
}

impl From<&CountAxis> for OwnedAxis {
    fn from(a: &CountAxis) -> Self {
        Self {
            id: OwnedAxisId::from(&a.id),
            name: a.name.to_string(),
        }
    }
}

impl From<CableKind> for OwnedCableKind {
    fn from(k: CableKind) -> Self {
        match k {
            CableKind::Mono => Self::Mono,
            CableKind::Poly => Self::Poly,
            CableKind::Stereo => Self::Stereo,
        }
    }
}

impl From<MonoLayout> for OwnedMonoLayout {
    fn from(l: MonoLayout) -> Self {
        match l {
            MonoLayout::Audio => Self::Audio,
            MonoLayout::Trigger => Self::Trigger,
        }
    }
}

impl From<PolyLayout> for OwnedPolyLayout {
    fn from(l: PolyLayout) -> Self {
        match l {
            PolyLayout::Audio => Self::Audio,
            PolyLayout::Trigger => Self::Trigger,
            PolyLayout::Transport => Self::Transport,
            PolyLayout::Midi => Self::Midi,
        }
    }
}

impl From<&PortTemplate> for OwnedPort {
    fn from(p: &PortTemplate) -> Self {
        Self {
            name: p.name.to_string(),
            kind: p.kind.clone().into(),
            mono_layout: p.mono_layout.into(),
            poly_layout: p.poly_layout.into(),
        }
    }
}

impl From<&ParameterKind> for OwnedParamKind {
    fn from(k: &ParameterKind) -> Self {
        match k {
            ParameterKind::Float { min, max, default } => Self::Float {
                min: *min,
                max: *max,
                default: *default,
            },
            ParameterKind::Int { min, max, default } => Self::Int {
                min: *min,
                max: *max,
                default: *default,
            },
            ParameterKind::Bool { default } => Self::Bool { default: *default },
            ParameterKind::Enum { variants, default } => Self::Enum {
                variants: variants.iter().map(|s| s.to_string()).collect(),
                default: default.to_string(),
            },
            ParameterKind::File { extensions } => Self::File {
                extensions: extensions.iter().map(|s| s.to_string()).collect(),
            },
            ParameterKind::SongName => Self::SongName,
        }
    }
}

impl From<&ParameterTemplate> for OwnedParam {
    fn from(p: &ParameterTemplate) -> Self {
        Self {
            name: p.name.to_string(),
            kind: (&p.kind).into(),
        }
    }
}

impl From<&ModuleDescriptorTemplate> for OwnedTemplate {
    fn from(t: &ModuleDescriptorTemplate) -> Self {
        let pair_port = |(a, p): &(AxisId, PortTemplate)| (OwnedAxisId::from(a), OwnedPort::from(p));
        let pair_param = |(a, p): &(AxisId, ParameterTemplate)| {
            (OwnedAxisId::from(a), OwnedParam::from(p))
        };
        Self {
            name: t.name.to_string(),
            axes: t.axes.iter().map(OwnedAxis::from).collect(),
            global_inputs: t.global_inputs.iter().map(OwnedPort::from).collect(),
            per_axis_inputs: t.per_axis_inputs.iter().map(pair_port).collect(),
            global_outputs: t.global_outputs.iter().map(OwnedPort::from).collect(),
            per_axis_outputs: t.per_axis_outputs.iter().map(pair_port).collect(),
            realtime_params: t.realtime_params.iter().map(OwnedParam::from).collect(),
            structural_params: t.structural_params.iter().map(OwnedParam::from).collect(),
            per_axis_realtime_params: t
                .per_axis_realtime_params
                .iter()
                .map(pair_param)
                .collect(),
            per_axis_structural_params: t
                .per_axis_structural_params
                .iter()
                .map(pair_param)
                .collect(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use patches_core::ParameterKind;

    fn sample_template() -> ModuleDescriptorTemplate {
        const T: ModuleDescriptorTemplate = ModuleDescriptorTemplate {
            name: "Mixer",
            axes: &[CountAxis::CHANNELS],
            global_inputs: &[PortTemplate::mono("cv")],
            per_axis_inputs: &[(AxisId::CHANNELS, PortTemplate::mono("in"))],
            global_outputs: &[],
            per_axis_outputs: &[(AxisId::CHANNELS, PortTemplate::mono("out"))],
            realtime_params: &[],
            structural_params: &[ParameterTemplate {
                name: "label",
                kind: ParameterKind::Bool { default: false },
            }],
            per_axis_realtime_params: &[(
                AxisId::CHANNELS,
                ParameterTemplate {
                    name: "gain",
                    kind: ParameterKind::Float { min: 0.0, max: 1.0, default: 1.0 },
                },
            )],
            per_axis_structural_params: &[],
        };
        T
    }

    #[test]
    fn owned_template_from_static_round_trip() {
        let t = sample_template();
        let owned = OwnedTemplate::from(&t);
        let json = serde_json::to_string(&owned).unwrap();
        let parsed: OwnedTemplate = serde_json::from_str(&json).unwrap();
        assert_eq!(owned, parsed);
    }

    #[test]
    fn manifest_round_trip() {
        let entry = ModuleManifestEntry {
            name: "Mixer".to_string(),
            template: OwnedTemplate::from(&sample_template()),
        };
        let manifest = ModuleManifest {
            schema_version: SCHEMA_VERSION,
            generator: GeneratorInfo {
                tool: "patches-manifest".to_string(),
                git_rev: "deadbeef".to_string(),
                timestamp: "2026-05-03T00:00:00Z".to_string(),
            },
            modules: vec![entry],
        };
        let json = serde_json::to_string(&manifest).unwrap();
        let parsed: ModuleManifest = serde_json::from_str(&json).unwrap();
        assert_eq!(manifest, parsed);
        assert_eq!(parsed.schema_version, SCHEMA_VERSION);
    }

    #[test]
    fn owned_template_preserves_per_axis_entries() {
        let t = sample_template();
        let owned = OwnedTemplate::from(&t);
        assert_eq!(owned.per_axis_inputs.len(), 1);
        assert_eq!(owned.per_axis_inputs[0].0 .0, "channels");
        assert_eq!(owned.per_axis_inputs[0].1.name, "in");
        assert_eq!(owned.per_axis_realtime_params.len(), 1);
        assert_eq!(owned.per_axis_realtime_params[0].1.name, "gain");
    }
}
