//! Shared DSP core for `VDco` and `VPolyDco`.
//!
//! One phase accumulator per voice drives saw, variable-width pulse, a
//! phase-locked ÷2 sub square, and a wavefolded triangle. Each waveform has
//! a continuous gain in `[0, 1]`. A white-noise source and an internal mixer
//! are folded into the same module so the output is a single pre-mixed signal.
//!
//! PolyBLEP corrections are applied at each waveshape's own discontinuities
//! and scale with the same gain as the raw waveform, preserving the
//! BLEP-to-raw ratio at any gain; the pulse comparator reads the raw phase
//! (never the BLEP-corrected saw), so duty cycle is bit-accurate.
//!
//! Triangle is generated by wavefolding the raw phase as
//! `tri = 1 - 2*|2*phase - 1|`, a standard absolute-value triangle at the fundamental (Jupiter
//! trick, fundamental variant). Its corners are C⁰ (slope discontinuities,
//! not value jumps), so no polyBLEP is used; residual aliasing is 6 dB/oct
//! below the saw and usually inaudible. A BLAMP refinement can be added
//! later if needed.

use patches_core::params_enum;
use patches_dsp::{fast_exp2, polyblep, xorshift64};

params_enum! {
    pub enum VDcoFmType {
        Linear => "linear",
        Logarithmic => "logarithmic",
    }
}

/// Linear FM scale — Hz per unit CV (matches `Osc`/`PolyOsc`).
const LINEAR_FM_HZ_PER_UNIT: f32 = 10.0;

/// Reference pitch: C0 ≈ 16.35 Hz. Duplicated from `patches-modules` to keep
/// `patches-vintage` free of the modules-crate dependency.
pub const C0_FREQ: f32 = 16.351_598;

/// Effective PWM range. Full travel (0 or 1) produces a DC-only pulse; the
/// clamp keeps the output audible at the extremes.
const PWM_MIN: f32 = 0.02;
const PWM_MAX: f32 = 0.98;

/// Internal scale on the noise source (≈ 0.5 full-scale at `noise_gain = 1`).
const NOISE_SCALE: f32 = 0.5;

/// Mixer settings (biased, not equal — worst-case sum ≈ 3.5× a single source).
#[derive(Clone, Copy)]
pub struct VDcoMix {
    pub saw_gain: f32,
    pub pulse_gain: f32,
    pub triangle_gain: f32,
    pub sub_gain: f32,
    pub noise_gain: f32,
    /// Always-on analog phasor curvature in `[0, 1]`. `0.0` is linear.
    pub curve: f32,
}

impl VDcoMix {
    pub const DEFAULT: Self = Self {
        saw_gain: 1.0,
        pulse_gain: 0.0,
        triangle_gain: 0.0,
        sub_gain: 0.0,
        noise_gain: 0.0,
        curve: 0.1,
    };
}

/// Quadratic approximation of the analog cap-charge curve, pinned at `0→0` and
/// `1→1`. `c = 0` reproduces the linear phasor bit-for-bit.
#[inline]
fn shape_phase(phase: f32, curvature: f32) -> f32 {
    phase - curvature * phase * (1.0 - phase)
}

/// Derivative of `shape_phase` w.r.t. phase — used to scale `dt` for polyBLEP.
#[inline]
fn shape_dt(dt: f32, phase: f32, curvature: f32) -> f32 {
    dt * (1.0 - curvature * (1.0 - 2.0 * phase))
}

/// Per-voice mutable state: phase, increment, sub flip-flop, noise PRNG.
pub struct VDcoVoice {
    pub phase: f32,
    pub phase_increment: f32,
    pub sub_flipflop: bool,
    pub prng_state: u64,
}

impl VDcoVoice {
    pub fn new(seed: u64) -> Self {
        Self {
            phase: 0.0,
            phase_increment: 0.0,
            sub_flipflop: false,
            // xorshift64 requires non-zero state.
            prng_state: seed.wrapping_add(1),
        }
    }
}

/// Phase increment per sample for `voct` (V/oct relative to C0).
///
/// Clamped below 1.0 so `advance` can wrap with a single conditional subtract.
#[inline]
pub fn voct_to_increment(voct: f32, sample_rate: f32) -> f32 {
    let freq = C0_FREQ * fast_exp2(voct);
    (freq / sample_rate).min(0.999_999)
}

/// Phase increment from V/oct + FM, selecting linear vs logarithmic FM.
///
/// `base_voct` is the baseline frequency param (V/oct offset from C0) plus any
/// connected `voct` CV. `fm` is the raw FM CV (0 if disconnected). For
/// `Logarithmic`, FM adds to the exponent (1 V/oct). For `Linear`, FM adds
/// `LINEAR_FM_HZ_PER_UNIT` Hz per unit CV, matching `Osc`/`PolyOsc`.
#[inline]
pub fn compute_increment(
    base_voct: f32,
    fm: f32,
    fm_type: VDcoFmType,
    fm_connected: bool,
    sample_rate: f32,
) -> f32 {
    let exp = base_voct + if fm_connected && fm_type == VDcoFmType::Logarithmic { fm } else { 0.0 };
    let mut freq = C0_FREQ * fast_exp2(exp);
    if fm_connected && fm_type == VDcoFmType::Linear {
        freq += fm * LINEAR_FM_HZ_PER_UNIT;
    }
    // Clamp non-negative so `advance` never runs backwards, and below 1.0 per
    // sample so the wrap is a single conditional subtract.
    (freq / sample_rate).clamp(0.0, 0.999_999)
}

/// Advance the phase by `phase_increment`, wrapping to `[0, 1)`. Toggles the
/// sub flip-flop on each wrap so the ÷2 square stays phase-locked.
#[inline]
pub fn advance(voice: &mut VDcoVoice) {
    let next = voice.phase + voice.phase_increment;
    if next >= 1.0 {
        voice.phase = next - 1.0;
        voice.sub_flipflop = !voice.sub_flipflop;
    } else {
        voice.phase = next;
    }
}

/// Render one mixed sample for `voice` using the current phase, then advance.
///
/// `pwm` is the raw PWM CV (clamped internally). The saw, pulse, and sub all
/// derive from the same raw `phase`, each with its own polyBLEP correction.
#[inline]
pub fn render_and_advance(voice: &mut VDcoVoice, pwm: f32, mix: &VDcoMix) -> f32 {
    let lin_phase = voice.phase;
    let lin_dt = voice.phase_increment;
    let c = mix.curve;
    // Shaped phase drives all waveform reads; accumulator still runs linearly
    // so the perceived fundamental is unchanged.
    let phase = shape_phase(lin_phase, c);
    let dt = shape_dt(lin_dt, lin_phase, c);

    let mut y = 0.0_f32;

    if mix.saw_gain > 0.0 {
        y += mix.saw_gain * ((2.0 * phase - 1.0) - polyblep(phase, dt));
    }

    if mix.pulse_gain > 0.0 {
        let pwm_c = pwm.clamp(PWM_MIN, PWM_MAX);
        let raw = if phase < pwm_c { 1.0 } else { -1.0 };
        let blep = polyblep(phase, dt) - polyblep((phase - pwm_c).rem_euclid(1.0), dt);
        y += mix.pulse_gain * (raw + blep);
    }

    if mix.triangle_gain > 0.0 {
        // Wavefolded triangle at the fundamental: tri = 1 - 2*|2*phase - 1|.
        let tri = 1.0 - 2.0 * (2.0 * phase - 1.0).abs();
        y += mix.triangle_gain * tri;
    }

    if mix.sub_gain > 0.0 {
        // Sub: half-rate square phase-locked to main via the flip-flop. The
        // same curvature shape applies so the sub reads a shaped phase too.
        let lin_sub_phase = lin_phase * 0.5 + if voice.sub_flipflop { 0.5 } else { 0.0 };
        let lin_sub_dt = lin_dt * 0.5;
        let sub_phase = shape_phase(lin_sub_phase, c);
        let sub_dt = shape_dt(lin_sub_dt, lin_sub_phase, c);
        let raw = if sub_phase < 0.5 { 1.0 } else { -1.0 };
        let blep =
            polyblep(sub_phase, sub_dt) - polyblep((sub_phase - 0.5).rem_euclid(1.0), sub_dt);
        y += mix.sub_gain * (raw + blep);
    }

    if mix.noise_gain > 0.0 {
        let w = xorshift64(&mut voice.prng_state);
        y += mix.noise_gain * NOISE_SCALE * w;
    }

    advance(voice);
    y
}
