[package]
name = "patches-vintage"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
patches-sdk = { path = "../patches-sdk" }
patches-dsp = { path = "../patches-dsp" }

[dev-dependencies]
patches-sdk = { path = "../patches-sdk", features = ["test-support"] }

[lib]
name = "patches_vintage"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
doctest = false
