[package]
name = "patches-fft-bundle"
version = "0.1.0"
edition = "2021"

[dependencies]
patches-sdk = { path = "../../patches-sdk" }
patches-dsp = { path = "../../patches-dsp" }
patches-fft-harness = { path = "../patches-fft-harness" }
patches-io = { path = "../../patches-io" }
rtrb = "0.3"

[dev-dependencies]
patches-sdk = { path = "../../patches-sdk", features = ["test-support"] }

[lib]
name = "patches_fft_bundle"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
doctest = false
