[package]
name = "patches-interpreter"
version = "0.6.0"
edition = "2021"
publish = false

[lib]
name = "patches_interpreter"
path = "src/lib.rs"
doctest = false

[dependencies]
patches-core = { path = "../patches-core" }
patches-dsl  = { path = "../patches-dsl" }

[dev-dependencies]
patches-modules = { path = "../patches-modules" }
